apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: laoj43upq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: laoj43upq-go 
  name: laoj43upq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: laoj43upq-go 
